### List all message 
GET http://localhost:3000/messages 

###
GET http://localhost:3000/messages/9

### Create a new message 
POST http://localhost:3000/messages 
content-Type: application/json

{
    "content": "Oe of the best messsages I have ever seen"
}
